#!/usr/bin/env bash


sleep 30

echo "Starting to test handlers"

NB_EMAILS=$(find /var/spool/postfix/defer* -type f | wc -l)

if [ $NB_EMAILS -eq 0 ]; then
    echo "There is no email generated by handlers, error"
    exit 2
fi

echo "Email handler OK"
