#!/usr/bin/env bash

/etc/init.d/postfix start


/etc/init.d/opsbro start

sleep 5

echo "Starting to test MAIL handlers"

NB_EMAILS_DEFERED=$(find /var/spool/postfix/defer* -type f | wc -l)
NB_EMAILS_ACTIVE=$(find /var/spool/postfix/active -type f | wc -l)


if [ $NB_EMAILS_DEFERED -eq 0 ] && [ $NB_EMAILS_ACTIVE -eq 0 ]; then
    echo "There is no mail generated by handlers, error active=$NB_EMAILS_ACTIVE  defered*=$NB_EMAILS_DEFERED "
    exit 2
fi

echo "Emails: Defered:$NB_EMAILS_DEFERED   Active:$NB_EMAILS_ACTIVE "

echo "DEFERED"
cat /var/spool/postfix/defer*/*
echo "ACTIVE"
cat /var/spool/postfix/active/*

echo "Email handler OK"
