#!/bin/bash

# NOTE: dnf have less parameter than yum

dnf  --nogpgcheck  -y     install $1
if [ $? == 0 ]; then
   exit 0
fi

dnf  --nogpgcheck  -y    install $1
if [ $? == 0 ]; then
   exit 0
fi

dnf  --nogpgcheck  -y   install $1

exit $?